#!/bin/bash

# Source global definitions
#==========================
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# User specific $PATH modifications
#==================================
if [ -f ~/.dotfiles/bash/path ]; then
  . ~/.dotfiles/bash/path
fi

# User specific aliases
#======================
if [ -f ~/.dotfiles/bash/aliases ]; then
  . ~/.dotfiles/bash/aliases
fi

# User specific prompt
#=====================
if [ -f ~/.dotfiles/bash/prompt ]; then
  . ~/.dotfiles/bash/prompt
fi

# Go specific options
#====================
if [ -f ~/.dotfiles/bash/go ]; then
  . ~/.dotfiles/bash/go
fi

# Common settings
#================

# Language
export LANG="en_US.UTF-8"

# Default editor
if [ -f /usr/bin/mcedit ]; then
  export EDITOR=/usr/bin/mcedit
else
  export EDITOR=/usr/bin/nano
fi

# Fix ANSI colors in less/more output
export LESS="-erX"

# SSH agent
#SSHAGENT=`which ssh-agent`
#SSHAGENTARGS="-s"
#if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
#  eval `$SSHAGENT $SSHAGENTARGS`
#  trap "kill $SSH_AGENT_PID" 0
#fi

# OS specific settings
if [[ $OSTYPE == darwin* ]]; then
  if [ -f ~/.dotfiles/darwin/bashrc ]; then
    . ~/.dotfiles/darwin/bashrc
  fi
fi

# History settings
export HISTFILESIZE=1000000000
export HISTSIZE=1000000
export HISTCONTROL=ignoreboth:erasedups   # no duplicate entries
shopt -s histappend                       # append history file
export PROMPT_COMMAND="history -a;${PROMPT_COMMAND}"        # update histfile after every command

# For PHP debugging
export PHP_IDE_CONFIG="serverName=$USER.$HOST"

