# Darwin (OS X) .bashrc

# Mac ports additions
#====================
export PATH=/opt/local/bin/:/opt/local/sbin/:$PATH

export PATH=$PATH:/usr/local/mysql/bin
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/mysql/lib

if [ -f /opt/local/etc/bash_completion ]; then
	. /opt/local/etc/bash_completion
fi

# Specific aliases
#=================

alias ll='/opt/local/bin/gls -l --color'
alias la='/opt/local/bin/gls -la --color'
