#!/bin/bash
# Show extra colored information in bash prompt:
#  * User rights and session type
#  * Information about background/stopped/screened processes
#  * Current dir (no more than 25% of line) and is it writable
#  * SCM (Git and SVN) branch and status info
#
# Based on:
#  * https://gist.github.com/31967
#  * http://www.debian-administration.org/articles/205

# OS X compatibility
if [[ $OSTYPE == darwin* ]]; then
  SED_REGEX="sed -E"
else
  SED_REGEX="sed -r"
fi

# The various escape codes that we can use to color our prompt.
        RED="\[\033[0;31m\]"
     YELLOW="\[\033[0;33m\]"
      GREEN="\[\033[0;32m\]"
       BLUE="\[\033[0;34m\]"
  LIGHT_RED="\[\033[1;31m\]"
LIGHT_GREEN="\[\033[1;32m\]"
 LIGHT_BLUE="\[\033[1;34m\]"
 LIGHT_CYAN="\[\033[1;36m\]"
      WHITE="\[\033[1;37m\]"
 LIGHT_GRAY="\[\033[0;37m\]"
 COLOR_NONE="\[\033[0m\]"

function get_prompt_jobs {
  # Information about background/stopped/screened processes.
  PROMPT_JOBS=""

  # Detached Screen Sessions
  local DTCHSCRN=$(screen -ls | grep -c Detach )
  if [[ ${DTCHSCRN} -gt 2 ]]; then
    PROMPT_JOBS="${PROMPT_JOBS}\[${COLOR_RED}\][scr:${DTCHSCRN}] "
  elif [[ ${DTCHSCRN} -gt 0 ]]; then
    PROMPT_JOBS="${PROMPT_JOBS}\[${COLOR_YELLOW}\][scr:${DTCHSCRN}] "
  fi

  # Backgrounded running jobs
  local BKGJBS=$(jobs -r | wc -l )
  if [[ ${BKGJBS} -gt 2 ]]; then
    PROMPT_JOBS="${PROMPT_JOBS}\[${COLOR_RED}\][bkg:${BKGJBS}]"
  elif [[ ${BKGJBS} -gt 0 ]]; then
    PROMPT_JOBS="${PROMPT_JOBS}\[${COLOR_YELLOW}\][bkg:${BKGJBS}] "
  fi

  # Stopped Jobs
  local STPJBS=$(jobs -s | wc -l )
  if [[ ${STPJBS} -gt 2 ]]; then
    PROMPT_JOBS="${PROMPT_JOBS}\[${COLOR_RED}\][stp:${STPJBS}]"
  elif [[ ${STPJBS} -gt 0 ]]; then
    PROMPT_JOBS="${PROMPT_JOBS}\[${COLOR_YELLOW}\][stp:${STPJBS}] "
  fi

  if [[ ${PROMPT_JOBS} != "" ]]; then
    PROMPT_JOBS=" ${PROMPT_JOBS}"
  fi

  echo ${PROMPT_JOBS}
}

# Trim working dir to 1/4 the screen width
function get_prompt_workingdir {
  local maxlen=$(($COLUMNS/4))
  local trunc_symbol="..."
  if [[ $PWD == $HOME* ]]; then
    newPWD="~${PWD#$HOME}" 
  else
    newPWD=${PWD}
  fi
  if [[ ${#newPWD} -gt $maxlen ]]; then
    local offset=$(( ${#newPWD} - $maxlen + 3 ))
    newPWD="${trunc_symbol}${newPWD:$offset:$maxlen}"
  fi

  echo $newPWD
}

# Detect whether the current directory is a git repository.
function is_git_repository {
  git branch --no-color > /dev/null 2>&1
}

# Determine the branch/state information for this git repository.
function get_prompt_git {
  # Capture the output of the "git status" command.
  git_status=$(git status --porcelain 2> /dev/null)

  # Output example:
  #
  #  ## master...origin/master
  #  A  1
  #   M phpunit.xml.dist
  #  ?? 2

  # Set color based on clean/staged/dirty.
  if [[ -z ${git_status} ]]; then
    state_color="${GREEN}"
  elif [[ ${git_status} =~ "?? " ]]; then
    state_color="${RED}"
  else
    state_color="${YELLOW}"
  fi

  # Get the name of the branch.
  branch_name=$(git rev-parse --abbrev-ref HEAD)
  if [[ ${branch_name} = "HEAD" ]]; then
    branch_name="detached HEAD"
  fi

  # Get the difference with remote tracking branch.
  ahead=$(git rev-list @{u}..HEAD --count)
  behind=$(git rev-list HEAD..@{u} --count)
  if [[ ${ahead} -gt 0 ]] && [[ ${behind} -eq 0 ]]; then
    sync_action=" ↑${ahead}"
  elif [[ ${ahead} -eq 0 ]] && [[ ${behind} -gt 0 ]]; then
    sync_action=" ↓${behind}"
  elif [[ ${ahead} -gt 0 ]] && [[ ${behind} -gt 0 ]]; then
    sync_action=" ↑${ahead} ↓${behind}"
  else
    sync_action=""
  fi

  # Combine the final branch string.
  echo "(± ${state_color}${branch_name}${COLOR_NONE}${sync_action})"
}

# Detect whether the current directory is a subversion repository.
function is_svn_repository {
  test -d .svn
}

# Determine the branch information for this subversion repository. No support
# for svn status, since that needs to hit the remote repository.
function get_prompt_svn {
  # Capture the output of the "git status" command.
  svn_info="$(svn info | egrep '^URL: ' 2> /dev/null)"

  # Get the name of the branch.
  branch_pattern="^URL: .*/(branches|tags)/([^/]+)"
  trunk_pattern="^URL: .*/trunk(/.*)?$"
  if [[ ${svn_info} =~ $branch_pattern ]]; then
    branch=${BASH_REMATCH[2]}
  elif [[ ${svn_info} =~ $trunk_pattern ]]; then
    branch='trunk'
  fi

  # Set the final branch string.
  echo "(${branch})"
}

# Return the prompt symbol to use, colorized based on the return value of the
# previous command.
function get_prompt_end_symbol {
  if [[ ${EUID} == 0 ]]; then
    symbol="#";
  else 
    symbol="\$"
  fi

  if test $1 -eq 0 ; then
      echo "${symbol}"
  else
      echo "${RED}${symbol}${COLOR_NONE}"
  fi
}

# Set the full bash prompt.
function set_bash_prompt {
  # Set the PROMPT_USER variable
  if [[ ${EUID} == 0 ]]; then
    local PROMPT_USER_HOST="${RED}\u@\h${COLOR_NONE}"
  else
    local PROMPT_USER_HOST="${GREEN}\u@\h${COLOR_NONE}"
  fi

  # Set the PROMPT_JOBS variable
  local PROMPT_JOBS=$(get_prompt_jobs)

  # Set the PROMPT_PWD variable
  if [ -w "${PWD}" ]; then
    local PROMPT_PWD="${LIGHT_BLUE}$(get_prompt_workingdir)${COLOR_NONE}"
    local PROMPT_PWD_SHORT="${LIGHT_BLUE}\W${COLOR_NONE}"
  else
    local PROMPT_PWD="${LIGHT_RED}$(get_prompt_workingdir)${COLOR_NONE}"
    local PROMPT_PWD_SHORT="${LIGHT_RED}\W${COLOR_NONE}"
  fi

  # Set the PROMPT_SCM variable (git/svn branch name and status)
  if is_git_repository ; then
    local PROMPT_SCM="$(get_prompt_git) "
  elif is_svn_repository ; then
    local PROMPT_SCM="$(get_prompt_svn) "
  else
    local SCM=""
  fi

  # Set the PROMPT_END variable. We do this first so we don't lose the 
  # return value of the last command.
  local PROMPT_END=$(get_prompt_end_symbol $?)

  # Set the bash prompt variable.
  PS1="${PROMPT_USER_HOST}:${PROMPT_JOBS} ${PROMPT_PWD} ${PROMPT_SCM}${PROMPT_END} "
  PS1FORTEST=$(echo $PS1 | $SED_REGEX 's/\\\[\\033\[[0-9]+;[0-9]+m\\\]//g')

  local ps1maxlen=$(($COLUMNS/2))

  # If very long: do not show full path
  if [[ ${#PS1FORTEST} -gt $ps1maxlen ]]; then
    PS1="${PROMPT_USER_HOST}:${PROMPT_JOBS} ${PROMPT_PWD_SHORT} ${PROMPT_SCM}${PROMPT_END} "
    PS1FORTEST=$(echo $PS1 | $SED_REGEX 's/\\\[\\033\[[0-9]+;[0-9]+m\\\]//g')
  fi

  # If still long: do not show full path and SCM status
  if [[ ${#PS1FORTEST} -gt $ps1maxlen ]]; then
    PS1="${PROMPT_USER_HOST}:${PROMPT_JOBS} ${PROMPT_PWD_SHORT} ${PROMPT_END} "
  fi
}

# Tell bash to execute this function just before displaying its prompt.
PROMPT_COMMAND=set_bash_prompt
